<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
b
Common.proto$Grpc.PHPdhtQbittorrentService.Common"$

Parameters

p1 (

p2 (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

