<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
6
Service.protoGrpc.PHPdhtQbittorrentServicebproto3'
        , true);

        static::$is_initialized = true;
    }
}

