version: '3'
networks:
  ggggg:
    external: true
services:
  hyperf3:
    build: .
    image: phpdht:qbittorrent_service
    container_name: qbittorrent_service
    privileged: false
    networks:
      - ggggg
    volumes:
      - .:/var/www/html
    tty: true
    command:
      - "bash"
    ports:
#      http
      - 35200:9501
      - 35201:9503

